packages:
  - integrations/*
  - ui/apps/*
  - ui/packages/*

allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - '@deepseek-ai/dsh-brand@0.1.7-rc.2'
  - '@deepseek-ai/dsh-typert-protocol@0.1.7-rc.2'
