const { chromium } = await import(process.env.FOCUS_PLAYWRIGHT_MODULE || 'playwright');
import assert from 'node:assert/strict';
import fs from 'node:fs';
const browser = await chromium.launch({headless:true,executablePath:process.env.FOCUS_CHROMIUM_EXECUTABLE || undefined,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--no-zygote']});
try {
  const page = await browser.newPage({viewport:{width:390,height:844}});
  const errors = [], dialogs = [], mutations = [];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('dialog',async dialog=>{dialogs.push(dialog.message());await dialog.dismiss()});
  page.on('request',request=>{if(request.method()==='POST' && /\/preparation\//.test(request.url())) mutations.push(request.url())});
  const api = async () => (await (await page.request.get('http://127.0.0.1:8765/reader/window')).json()).value;
  await page.goto('http://127.0.0.1:8765/library');
  const card = page.locator('.library-card').first();
  await card.getByRole('button',{name:'详细',exact:true}).click();
  await card.getByText('准备超时',{exact:true}).waitFor();
  assert.equal(await card.getByRole('button',{name:'重试',exact:true}).isEnabled(),true);
  const before = await api();
  const acknowledgement = page.waitForResponse(response=>response.url().endsWith('/preparation/dismiss') && response.request().method()==='POST');
  await card.getByRole('button',{name:'关闭准备阅读提示',exact:true}).click();
  assert.equal(await card.locator('.preparation-notice').count(),0);
  const saved = await (await acknowledgement).json();
  assert.equal(saved.ok,true);
  assert.equal(saved.value.preparations['fixture-paper'].dismissed,true);
  assert.deepEqual(dialogs,[]);
  assert.equal(mutations.filter(url=>/\/(resume|cancel)$/.test(url)).length,0);
  const closed = await api();
  assert.equal(closed.preparations['fixture-paper'].status,'failed');
  assert.equal(closed.readingRevision,before.readingRevision);
  assert.deepEqual(closed.readingProgress,before.readingProgress);
  assert.deepEqual(closed.navigationCurrent,before.navigationCurrent);
  assert.equal(closed.workItems.some(item=>item.kind==='preparation'),false);
  await page.reload();
  await card.getByRole('button',{name:'详细',exact:true}).click();
  await page.getByRole('button',{name:'任务详情',exact:true}).click();
  assert.equal(await page.locator('.preparation-notice').count(),0);
  assert.equal(mutations.filter(url=>/\/(resume|cancel)$/.test(url)).length,0);
  await page.getByRole('button',{name:'任务详情',exact:true}).click();
  await page.screenshot({path:`${process.env.FOCUS_BROWSER_OUTPUT || '/tmp'}/preparation-dismissed.png`});
  // The fixture deliberately fails the next candidate plan, proving a new attempt reappears.
  await card.getByRole('button',{name:'准备阅读',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('.library-card .preparation-notice')?.textContent.includes('准备失败'));
  const restarted = await api();
  assert.notEqual(restarted.preparations['fixture-paper'].attempt,before.preparations['fixture-paper'].attempt);
  assert.equal(restarted.preparations['fixture-paper'].dismissed,false);
  const stale = await page.request.post('http://127.0.0.1:8765/library/sources/fixture-paper/preparation/dismiss',{data:{attempt:before.preparations['fixture-paper'].attempt}});
  assert.equal((await stale.json()).ok,false);
  assert.equal((await api()).preparations['fixture-paper'].dismissed,false);
  await page.screenshot({path:`${process.env.FOCUS_BROWSER_OUTPUT || '/tmp'}/preparation-new-attempt.png`});
  assert.deepEqual(errors,[]);
  const result={checks:['timeout has Retry and Close','close hides immediately without confirmation or cancelling/retrying','reload keeps prompt hidden','reading progress preserved','explicit preparation creates visible new attempt','stale dismissal cannot hide new attempt'],errors};
  fs.writeFileSync(`${process.env.FOCUS_BROWSER_OUTPUT || '/tmp'}/preparation-dismiss-results.json`,JSON.stringify(result,null,2));
  console.log(JSON.stringify(result));
} finally { await browser.close(); }
