const {chromium}=await import(process.env.FOCUS_PLAYWRIGHT_MODULE || 'playwright');
import assert from 'node:assert/strict';
import fs from 'node:fs';
const output=process.env.FOCUS_BROWSER_OUTPUT || '/tmp';
const browser=await chromium.launch({headless:true,executablePath:process.env.FOCUS_CHROMIUM_EXECUTABLE || undefined,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--no-zygote']});
const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
page.setDefaultTimeout(10000);
const errors=[], posts=[], results=[];
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()==='POST')posts.push(r.url())});
const api=async()=>(await (await page.request.get('http://127.0.0.1:8765/reader/window')).json()).value;
const reader=page.locator('.focus-reader'), stream=page.locator('.focus-stream'), side=page.locator('.reader-side-space'), gallery=page.locator('.reader-figure-scroll');
const toolbar=page.getByRole('navigation',{name:'阅读侧栏'});
const chunk=async i=>page.waitForFunction(n=>document.querySelector('.focus-output[data-current-output="true"]')?.textContent.includes(`Section ${n}`),i);
const next=async i=>{await page.getByRole('button',{name:'继续',exact:true}).click();await chunk(i);};
const top=()=>stream.evaluate(el=>el.scrollTop);
const stable=async(before)=>{await page.waitForTimeout(100);assert.ok(Math.abs(await top()-before)<2,`text scroll moved: ${before} -> ${await top()}`)};
const cursor=v=>JSON.stringify({source:v.source,position:v.navigationCurrent?.chunkId,revision:v.readingRevision,progress:v.readingProgress});
try {
await page.goto('http://127.0.0.1:8765/reading');await chunk(1);
await page.waitForFunction(()=>document.querySelector('.reader-figure-scroll img')?.naturalWidth>0);
assert.equal(await gallery.locator('figure').count(),1);assert.equal(await stream.locator('img').count(),0);
const initialText=await stream.boundingBox(), initialSide=await side.boundingBox();
assert.ok(initialText.x+initialText.width<=initialSide.x);assert.ok(initialText.height>600);
assert.ok(initialText.width/(initialText.width+initialSide.width)>.55 && initialText.width/(initialText.width+initialSide.width)<.65);
assert.equal(await page.locator('.reader-figure-navigation').getAttribute('open'),null);
assert.ok((await gallery.innerText()).includes('图 1：完整架构图注'));
await stream.hover();await page.mouse.wheel(0,430);await page.waitForTimeout(100);
assert.ok(await top()>200);assert.ok(await gallery.locator('img').isVisible());
await page.screenshot({path:`${output}/focus-figures-desktop.png`});results.push('Desktop 60/40 layout; long text and a large image scroll independently');
const before=cursor(await api()), beforePosts=posts.length;
await page.getByRole('textbox',{name:'输入问题或阅读需求'}).fill('第一段的草稿');
let position=await top();
await toolbar.getByRole('button',{name:'全文图片',exact:true}).click();await stable(position);
await page.getByText('图片导航',{exact:true}).click();await stable(position);
assert.equal(await gallery.locator('figure').count(),5);
await page.getByRole('navigation',{name:'图片目录'}).getByRole('button',{name:/图 5/}).click();await stable(position);
assert.ok(await gallery.evaluate(el=>el.scrollTop)>0);
assert.ok((await side.innerText()).includes('全文图片'));
assert.equal(cursor(await api()),before);assert.equal(posts.length,beforePosts);
await page.getByRole('button',{name:'返回本段图片',exact:true}).click();await stable(position);
await toolbar.getByRole('button',{name:'隐藏图片区',exact:true}).click();await stable(position);
assert.equal(await reader.getAttribute('data-side-open'),'false');
const centered=await page.locator('.focus-content').boundingBox(), expanded=await stream.boundingBox();
assert.ok(centered.width<=850);assert.ok(Math.abs(centered.x+centered.width/2-(expanded.x+expanded.width/2))<10);
const inline=stream.getByRole('button',{name:'查看图 1',exact:true});
await inline.scrollIntoViewIfNeeded();position=await top();await inline.click();await stable(position);
// Repeated links relocate the same selected figure after an independent gallery scroll.
await toolbar.getByRole('button',{name:'全文图片',exact:true}).click();
await page.getByText('图片导航',{exact:true}).click();
await page.getByRole('navigation',{name:'图片目录'}).getByRole('button',{name:/图 5/}).click();
await gallery.evaluate(el=>el.scrollTop=0);
await page.getByRole('navigation',{name:'图片目录'}).getByRole('button',{name:/图 5/}).click();
assert.ok(await gallery.evaluate(el=>el.scrollTop)>0);await stable(position);
results.push('Unread HTML/Markdown figures, repeated selection, hidden-panel centering; no POST, Cursor or progress changes');
await page.getByRole('button',{name:'返回本段图片',exact:true}).click();
const zoom=page.getByRole('button',{name:'放大图 1',exact:true});await zoom.click();
const modal=page.getByRole('dialog',{name:'图片放大'});
assert.equal(await modal.evaluate(el=>el.matches(':modal')),true);
await modal.getByRole('button',{name:'原尺寸查看',exact:true}).click();
assert.ok(await page.locator('.reader-image-viewport').evaluate(el=>el.scrollWidth>el.clientWidth));
await page.keyboard.press('Escape');assert.equal(await modal.isVisible(),false);
assert.equal(await zoom.evaluate(el=>el===document.activeElement),true);await stable(position);
await zoom.click();await modal.getByRole('button',{name:'关闭放大',exact:true}).click();assert.equal(await zoom.evaluate(el=>el===document.activeElement),true);await stable(position);
await toolbar.getByRole('button',{name:'笔记与记录',exact:true}).click();await stable(position);
assert.equal(await gallery.count(),0);assert.ok(await page.getByRole('complementary',{name:'笔记与阅读记录'}).isVisible());
await side.getByRole('button',{name:'图片',exact:true}).click();await stable(position);
const separator=page.getByRole('separator',{name:'调整文字与侧栏宽度'});const oldWidth=(await stream.boundingBox()).width;
await separator.focus();await page.keyboard.press('ArrowRight');await stable(position);
assert.ok((await stream.boundingBox()).width>oldWidth);
await page.keyboard.press('Home');
const sepBox=await separator.boundingBox();await page.mouse.move(sepBox.x+4,sepBox.y+100);await page.mouse.down();await page.mouse.move(sepBox.x+60,sepBox.y+100);await page.mouse.up();await stable(position);
assert.ok((await stream.boundingBox()).width>=340 && (await side.boundingBox()).width>=280);
results.push('Modal top layer, natural-size overflow, Close/Escape/focus restoration, shared notes space, keyboard/pointer resizing');
// Original switch updates the caption without a second gallery image or translation request.
await stream.getByRole('button',{name:'查看原文',exact:true}).click();
assert.ok((await gallery.innerText()).includes('Figure 1. Full architecture caption'));assert.equal(await gallery.locator('figure').count(),1);
await stream.getByRole('button',{name:'查看译文',exact:true}).click();
assert.ok((await gallery.innerText()).includes('图 1：完整架构图注'));assert.equal(posts.length,beforePosts);
await next(2);assert.equal(await gallery.locator('figure').count(),2);
position=await top();await gallery.hover();await page.mouse.wheel(0,550);await page.waitForTimeout(100);
assert.ok(await gallery.evaluate(el=>el.scrollTop)>0);await stable(position);
await stream.getByRole('button',{name:'查看图 3',exact:true}).click();await stable(position);
assert.ok(await gallery.evaluate(el=>el.scrollTop)>0);
assert.match(await gallery.locator('figure[data-selected=true] img').getAttribute('src'),/image-003/);
await page.getByRole('button',{name:'发送 ↑',exact:true}).click();
await page.waitForFunction(()=>document.querySelector('.workspace-status')?.textContent.includes('当前无工作'));
let view=await api();assert.equal(view.conversation[0].reference.chunkId,'chunk-001');
results.push('Language captions, multi-image scroll/inline targeting, pre-navigation draft still bound to Chunk 1');
await next(3);assert.equal(await reader.getAttribute('data-side-open'),'false');
position=await top();await toolbar.getByRole('button',{name:'全文图片',exact:true}).click();await stable(position);
await page.getByText('图片导航',{exact:true}).click();await page.getByRole('navigation',{name:'图片目录'}).getByRole('button',{name:/图 4/}).click();await stable(position);
assert.equal((await api()).navigationCurrent.index,3);
await next(4);assert.equal(await gallery.locator('figure').count(),2);
assert.ok(await stream.locator('.focus-output[data-current-output=true] table img').isVisible());
assert.ok(await stream.locator('.focus-output[data-current-output=true] .katex').isVisible());
assert.ok(await stream.locator('.focus-output[data-current-output=true] img[alt="Equation 1"]').isVisible());
const historyBefore=cursor(await api());
await page.getByRole('navigation',{name:'段落目录'}).getByRole('button',{name:/02/}).click();await chunk(2);
assert.equal(await gallery.locator('figure').count(),2);assert.equal(cursor(await api()),historyBefore);
await next(3);assert.equal(await reader.getAttribute('data-side-open'),'false');assert.equal(cursor(await api()),historyBefore);
results.push('No-image chunk, full-source access, formula/table retention, next/review defaults and history Continue preserve frontier');
// Source switches discard the old selection and draft scope.
await toolbar.getByRole('button',{name:'全文图片',exact:true}).click();await page.getByText('图片导航',{exact:true}).click();
await page.getByRole('navigation',{name:'图片目录'}).getByRole('button',{name:/图 5/}).click();
await page.getByRole('combobox',{name:'选择阅读材料',exact:true}).selectOption('second-paper');
await page.waitForFunction(()=>document.querySelector('.reader-figure-scroll img')?.getAttribute('src').includes('/second-paper/'));
assert.equal(await gallery.locator('figure').count(),1);assert.equal(await gallery.locator('img[src*="fixture-paper"]').count(),0);
await page.reload();await page.waitForFunction(()=>document.querySelector('.reader-figure-scroll img')?.getAttribute('src').includes('/second-paper/'));
assert.equal((await api()).navigationCurrent.index,1);
results.push('Source isolation, clear full-source selection and refresh recovery');
// Discussion reuses the source gallery, while external illustrations stay usable in text.
await page.route('https://example.invalid/extra.png',route=>route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jf4sAAAAASUVORK5CYII=','base64')}));
await page.getByRole('textbox',{name:'输入问题或阅读需求'}).fill('图片讨论验收');await page.getByRole('button',{name:'发送 ↑',exact:true}).click();
await page.locator('[data-role="assistant"]').getByRole('button',{name:'查看图 5',exact:true}).waitFor();
const answer=page.locator('[data-role="assistant"]').last();assert.equal(await answer.locator('img').count(),1);
assert.ok(await answer.getByRole('img',{name:'External illustration'}).isVisible());
position=await top();await answer.getByRole('button',{name:'查看图 5',exact:true}).click();await stable(position);
assert.ok((await side.innerText()).includes('全文图片'));
results.push('Discussion source images become gallery links; outside-catalogue image remains inline');
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(100);
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
assert.ok(await side.isVisible());assert.equal(await separator.isVisible(),false);
await page.screenshot({path:`${output}/focus-figures-narrow.png`});
await side.getByRole('button',{name:'关闭阅读侧栏',exact:true}).click();assert.equal(await reader.getAttribute('data-side-open'),'false');
await toolbar.getByRole('button',{name:'全文图片',exact:true}).click();
await page.keyboard.press('Escape');assert.equal(await reader.getAttribute('data-side-open'),'false');
assert.ok((await page.getByRole('button',{name:'继续',exact:true}).boundingBox()).y<844);
results.push('390px drawer, no horizontal overflow, close/Escape and Continue remain accessible');
assert.deepEqual(errors,[]);
fs.writeFileSync(`${output}/focus-figures-browser-results.json`,JSON.stringify({results,errors},null,2));console.log(JSON.stringify({results,errors}));
} catch(error) {await page.screenshot({path:`${output}/focus-figures-failure.png`});console.error(error);throw error;}
finally {await browser.close();}
